// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremierLeagueFantasyApp.Data;

#nullable disable

namespace PremierLeagueFantasyApp.Migrations
{
    [DbContext(typeof(FantasyStatsContext))]
    [Migration("20251013153554_FixPricePrecision")]
    partial class FixPricePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PremierLeagueFantasyApp.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Assists")
                        .HasColumnType("int");

                    b.Property<int>("CleanSheets")
                        .HasColumnType("int");

                    b.Property<int>("Goals")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Assists = 5,
                            CleanSheets = 0,
                            Goals = 27,
                            Name = "Haaland",
                            Position = "Forward",
                            Price = 14.0m,
                            Team = "MCI",
                            TotalPoints = 250
                        },
                        new
                        {
                            Id = 2,
                            Assists = 12,
                            CleanSheets = 0,
                            Goals = 18,
                            Name = "Salah",
                            Position = "Midfielder",
                            Price = 13.0m,
                            Team = "LIV",
                            TotalPoints = 230
                        },
                        new
                        {
                            Id = 3,
                            Assists = 10,
                            CleanSheets = 15,
                            Goals = 1,
                            Name = "Trippier",
                            Position = "Defender",
                            Price = 6.5m,
                            Team = "NEW",
                            TotalPoints = 200
                        },
                        new
                        {
                            Id = 4,
                            Assists = 10,
                            CleanSheets = 0,
                            Goals = 14,
                            Name = "Saka",
                            Position = "Midfielder",
                            Price = 9.0m,
                            Team = "ARS",
                            TotalPoints = 210
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
